# Generated by Django 4.1.2 on 2022-10-09 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('original_crime_type_name', models.CharField(max_length=50)),
                ('report_date', models.DateTimeField()),
                ('call_date', models.DateTimeField()),
                ('offense_date', models.DateTimeField()),
                ('call_time', models.TimeField()),
                ('call_date_time', models.DateTimeField()),
                ('disposition', models.CharField(max_length=12)),
                ('adress', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=50)),
                ('agency_id', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('adress_type', models.CharField(max_length=50)),
                ('common_location', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
